const createError = require("../utils/createError");
exports.createReply = async () => {
  try {
  } catch (error) {
    next(error);
  }
};

exports.updateReply = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
exports.deleteReply = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
