const createError = require("../utils/createError");
exports.createReply = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};

exports.updateReply = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};
exports.deleteReply = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};
